# 本科所学线性代数梳理


## 一般都是考研数学的范畴代码实现


## 行列式

In [4]:
#P92
import numpy as np
A = np.array([[1,0,0],[0,1,0],[0,0,5]])
d = np.linalg.det(A)  #完成计算行列式值的过程
print(d)

4.999999999999999


In [5]:
#P92
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.linalg.det(A)
print(d)

0.0


## 矩阵

In [1]:
#P69
import numpy as np
A=np.array([[1,0],[0,1]])
B=np.array([[4,1],[2,2]])
C=np.dot(A,B)       #完成矩阵相乘
print(C)

[[4 1]
 [2 2]]


In [2]:
#P77
import numpy as np
A=np.array([[1,0,0],[0,1,0],[0,0,5]])
B=np.linalg.inv(A)   #完成计算逆矩阵的过程
print(B)

[[1.  0.  0. ]
 [0.  1.  0. ]
 [0.  0.  0.2]]


## 线性方程组

In [5]:
#P97
import numpy as np
A = np.array([[3,1],[1,2]])
b = np.array([9,8])
x = np.linalg.solve(A,b)  #完成求解该方程组的过程
print(x)

[2. 3.]


## 特征值和特征向量

In [6]:
#P100
import numpy as np
A = np.array([[1,0,0],[0,1,0],[0,0,5]])
eigvalues,eigvectors = np.linalg.eig(A)
print(eigvalues)     #完成该矩阵特征值和特征向量的过程
print(eigvectors)

[1. 1. 5.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 接下来是研究生的矩阵论


## 矩阵的分解


In [9]:
#P123
import numpy as np
A=np.array([[6,3,4,8],[3,6,5,1],[4,5,10,7],[8,1,7,25]])
L=np.linalg.cholesky(A)  #该函数实现了对称的楚列斯基分解，函数的输入是被分解矩阵A，输出为下三角矩阵L
print(L)

[[ 2.44948974  0.          0.          0.        ]
 [ 1.22474487  2.12132034  0.          0.        ]
 [ 1.63299316  1.41421356  2.30940108  0.        ]
 [ 3.26598632 -1.41421356  1.58771324  3.13249102]]


In [10]:
#P127
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
Q,R=np.linalg.qr(A)   #实现QR分解
print(Q)
print(R)

[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


In [12]:
#P127
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
Q,R=np.linalg.qr(A)
print(Q)
print(R)

[[-0.24253563 -0.9701425 ]
 [-0.9701425   0.24253563]]
[[-4.12310563 -5.33578375 -6.54846188]
 [ 0.         -0.72760688 -1.45521375]]


In [11]:
#P132
from numpy import *
data = [[1,2,3],[4,5,6]]
u,sigma,vt=linalg.svd(data)    #SVD分解（适用于满秩分解）
print(u)
print(sigma)
print(vt)

[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
[9.508032   0.77286964]
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


In [12]:
#P129
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
V,U=np.linalg.eig(A)    #求解特征值，单位化特征向量
print(U) 
print(V)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [7]:
#P115
import numpy as np
A=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
n=np.linalg.norm(A,ord=2)   #计算矩阵范数的功能。函数的输入参数为要计算的矩阵，以及范数的类型，如果类型值为2，则计算谱范数。
print(n)

22.409298163270435


## 广义逆

##左右逆有问题

In [22]:
import numpy as np

# 定义一个矩阵
A = np.array([[4, 5, 0], [0, 5, 0]])

# 计算矩阵的广义逆
A_pinv = np.linalg.pinv(A)

print("Matrix A:")
print(A)

print("\nPseudo-Inverse of A:")
print(A_pinv)

# 计算左逆
left_inverse = np.dot(A_pinv, A)

# 计算右逆
right_inverse = np.dot(A, A_pinv)

print("\nLeft Inverse of A:")
print(left_inverse)

print("\nRight Inverse of A:")
print(right_inverse)

Matrix A:
[[4 5 0]
 [0 5 0]]

Pseudo-Inverse of A:
[[ 2.50000000e-01 -2.50000000e-01]
 [ 4.48057086e-17  2.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00]]

Left Inverse of A:
[[1.00000000e+00 2.77555756e-16 0.00000000e+00]
 [1.79222834e-16 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]

Right Inverse of A:
[[1.00000000e+00 2.77555756e-16]
 [2.24028543e-16 1.00000000e+00]]


In [19]:
import numpy as np

# 定义一个矩阵
A = np.array([[1,0,-1,1],[0,2,2,2],[-1,4,5,3]])

# 计算矩阵的广义逆
A_pinv = np.linalg.pinv(A)

print("Matrix A:")
print(A)

print("\nPseudo-Inverse of A:")
print(A_pinv)

Matrix A:
[[ 1  0 -1  1]
 [ 0  2  2  2]
 [-1  4  5  3]]

Pseudo-Inverse of A:
[[ 2.77777778e-01  1.11111111e-01 -5.55555556e-02]
 [ 5.55555556e-02  5.55555556e-02  5.55555556e-02]
 [-2.22222222e-01 -5.55555556e-02  1.11111111e-01]
 [ 3.33333333e-01  1.66666667e-01  2.99359462e-17]]


In [21]:
#再重新试一遍，分数很不好表示
import numpy as np

# 定义一个矩阵
A = np.array([[1,-1],[0,0]])

# 计算矩阵的广义逆
A_pinv = np.linalg.pinv(A)

print("Matrix A:")
print(A)

print("\nPseudo-Inverse of A:")
print(A_pinv)

Matrix A:
[[ 1 -1]
 [ 0  0]]

Pseudo-Inverse of A:
[[ 0.5  0. ]
 [-0.5  0. ]]


## 矩阵条件数

In [8]:
#P116
import numpy as np
A = np.array([[1,0,0],[0,1,0],[0,0,5]])
c=np.linalg.cond(A)    #计算矩阵条件数的功能
print(c)

5.0


## Kroneckor积和Hadamard积
### Kroneckor积

In [14]:
import numpy as np

# 定义两个矩阵
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 计算Kronecker积
kron_result = np.kron(A, B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nKronecker Product of A and B:")
print(kron_result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Kronecker Product of A and B:
[[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]


### Hadamard积

In [15]:
import numpy as np

# 定义两个矩阵
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 计算Hadamard积
hadamard_result = A * B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nHadamard Product of A and B:")
print(hadamard_result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Hadamard Product of A and B:
[[ 5 12]
 [21 32]]


#看的乱花渐欲迷人眼，试试小数分数转换

In [24]:
from fractions import Fraction

# 将小数转换为分数
decimal_number = 1.11111111e-01
fraction_result = Fraction(decimal_number).limit_denominator()

print("Decimal Number:", decimal_number)
print("Fraction Result:", fraction_result)

Decimal Number: 0.111111111
Fraction Result: 1/9
